import { Metadata } from 'next';

export const metadata: Metadata = {
  title: {
    default: 'RS Shonjoy',
    template: '%s | RS Shonjoy',
  },
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <header
          style={{
            backgroundColor: 'lavender',
            padding: '1rem',
          }}
        >
          <p>Header</p>
        </header>
        {children}
        <footer
          style={{
            backgroundColor: 'ghostwhite',
            padding: '1rem',
          }}
        >
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
